name: Applications CI/CD
on: [push, pull_request]

jobs:
  demo-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build demo app
        run: npm run build:demo
      - name: Test demo app
        run: npm run test:demo
      - name: E2E tests
        run: npm run test:e2e:demo
        env:
          CI: true
  
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build documentation
        run: npm run build:docs
      - name: Validate documentation links
        run: npm run validate:docs
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist
  
  marketplace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build marketplace
        run: npm run build:marketplace
      - name: Test marketplace API
        run: npm run test:marketplace
      - name: Test plugin registry
        run: npm run test:registry
