name: Applications CI/CD
on: [push, pull_request]

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  demo-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            apps/demo-analytics/package-lock.json
      - name: Install root dependencies
        run: npm ci
      - name: Install demo app dependencies
        run: cd apps/demo-analytics && npm ci
      - name: Build demo app
        run: npm run build:demo
      - name: Test demo app
        run: npm run test:demo
      - name: E2E tests
        run: npm run test:e2e:demo
        env:
          CI: true
  
  documentation:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            apps/docs/package-lock.json
      - name: Install root dependencies
        run: npm ci
      - name: Install docs dependencies
        run: cd apps/docs && npm ci
      - name: Build documentation
        run: npm run build:docs
      - name: Validate documentation links
        run: npm run validate:docs
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4
      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './apps/docs/.vitepress/dist'
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4
  
  marketplace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install root dependencies
        run: npm ci
      - name: Build marketplace
        run: npm run build:marketplace
      - name: Test marketplace API
        run: npm run test:marketplace
      - name: Test plugin registry
        run: npm run test:registry
